version: 2
registries:
  nuget-public:
    type: nuget-feed
    url: api.nuget.org
  bepinex:
    type: nuget-feed
    url: nuget.bepinex.dev
updates:
  - directory: /
    package-ecosystem: nuget
    ignore:
      - dependency-name: BepInEx.Core
      - dependency-name: HarmonyX
      - dependency-name: UnityEngine.Modules
    schedule:
      interval: daily
    registries:
      - nuget-public
      - bepinex 
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: daily
